/*
 * Copyright (c) 2017 - 2025, The casual project. All rights reserved.
 *
 * This software is licensed under the MIT license, https://opensource.org/licenses/MIT
 */

allprojects {
    plugins.withType(JavaPlugin) {
        sourceSets {
            integration {
                compileClasspath += sourceSets.main.output
                runtimeClasspath += sourceSets.main.output
            }
        }
        configurations {
            integrationImplementation.extendsFrom testCompile
            integrationRuntimeOnly.extendsFrom testRuntime
        }

        task intTest(type: Test) {
            description = 'Run integration tests'
            group = 'verification'
            testClassesDirs = sourceSets.integration.output.classesDirs
            classpath = sourceSets.integration.runtimeClasspath
        }

        test {
            useJUnitPlatform()
        }
        intTest{
            useJUnitPlatform()
        }
        
    }
}