/*
 * Copyright (c) 2017 - 2025, The casual project. All rights reserved.
 *
 * This software is licensed under the MIT license, https://opensource.org/licenses/MIT
 */

plugins {
  id 'war'
  id 'jacoco'
}

dependencies {
  api project(':casual:casual-api')
  compileOnly libs.javaee_api
  compileOnly libs.jakarta_annotation_api
  compileOnly libs.gson
}

war {
  archiveFileName = 'casual-jca-cli.war'
}

jar {
  enabled = false
}

sourceSets {
  main {
    java {
      srcDirs = ['src/main/java', "${buildDir}/generated/src/main/java"]
    }
  }
}

javadocJar.enabled = false
sourcesJar.enabled = false