/*
 * Copyright (c) 2017 - 2025, The casual project. All rights reserved.
 *
 * This software is licensed under the MIT license, https://opensource.org/licenses/MIT
 */

plugins {
  id 'war'
  id 'jacoco'
  id("org.openapi.generator") version "7.0.0"
}

dependencies {
  api project(':casual:casual-api')
  compileOnly libs.javaee_api
  compileOnly libs.jakarta_annotation_api
  compileOnly libs.gson
}

war {
  archiveFileName = 'casual-jca-cli.war'
}

jar {
  enabled = false
}

sourceSets {
  main {
    java {
      srcDirs = ['src/main/java', "${buildDir}/generated/src/main/java"]
    }
  }
}

openApiGenerate {
  generatorName.set("java")
  inputSpec.set("$projectDir/src/main/resources/openapi.yaml")
  outputDir.set("${buildDir}/generated")
  modelPackage.set("se.laz.casual.connection.jca.cli.model")
  skipValidateSpec.set(true)
  library.set("rest-assured")
  globalProperties.set([
      modelDocs: "false",
      apis: "false",
      models: "",
      modelTests: "false"
  ])
  configOptions.put("dateLibrary", "java8")
  configOptions.put("useJakartaEe", "true")
}

compileJava.dependsOn tasks.openApiGenerate
javadocJar.enabled = false
sourcesJar.enabled = false