/*
 * Copyright (c) 2017 - 2026, The casual project. All rights reserved.
 *
 * This software is licensed under the MIT license, https://opensource.org/licenses/MIT
 */

//-*- coding: utf-8 -*-
plugins {
    id 'java-library'
    id 'jacoco'
    id 'groovy'
    id "me.champeau.jmh" version "0.7.3"
}

defaultTasks 'build'

dependencies {
  api libs.netty
  api project(':casual:casual-api')

  // for spock
  testImplementation platform(libs.groovy_bom)
  testImplementation libs.groovy
  testImplementation platform(libs.spock_bom)
  testImplementation libs.spock_core
  testImplementation libs.byte_buddy
  testImplementation libs.objenesis

    jmh project(":casual:casual-network")

    jmh 'org.openjdk.jmh:jmh-core:1.36'
    jmh 'org.openjdk.jmh:jmh-generator-annprocess:1.36'

    // this is the line that solves the missing /META-INF/BenchmarkList error
    jmhAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.36'
}
