name: Release and Update Changelog

on:
  push:
    branches:
      - feature/not-dev  # will be dev when used for real

jobs:
  release-and-update:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Validate Commit Message
        run: |
          python validate_commit_message.py
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Update Changelog and Tag Release
        run: |
          python update_changelog_and_tag.py

      - name: Commit and push changelog changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add CHANGELOG.md
          git commit -m "chore(changelog): auto update for version $(grep 'version' versions.gradle | cut -d "'" -f2) [skip ci]" || echo "No changes to commit"
          git push

      - name: Push the tag
        run: |
          git push origin --tags
