name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
